# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: blackhacker511
open_collective: blacknet
ko_fi: blackhacker
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: BlackHacker
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
